services:
  
  db:
    container_name: db
    image: postgres
    restart: unless-stopped
    env_file:
      - ./db/settings.env
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    ports:
      - 5432:5432

volumes:
  pg-data:
    name: postgres-container_pgdata
